kind: Service
apiVersion: v1
metadata:
  name: orderservice
  labels:
    app: orderservice
spec:
  selector:
    app: orderservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
  labels:
    app: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "orderservice"
        dapr.io/app-port: "3000"
    spec:
      containers:
      - name: orderservice
        image: hynn/orderservice:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
