kind: Service
apiVersion: v1
metadata:
  name: stockservice
  labels:
    app: stockservice
spec:
  selector:
    app: stockservice
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3001
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockservice
  labels:
    app: stockservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stockservice
  template:
    metadata:
      labels:
        app: stockservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "stockservice"
        dapr.io/app-port: "3001"
    spec:
      containers:
      - name: stockservice
        image: danyaow/stockservice:latest
        ports:
        - containerPort: 3001
        imagePullPolicy: Always